# adapted from https://github.com/denoland/std/blob/main/.github/workflows/workspace_publish.yml

name: ci

on:
  push:
    branches:
      - main
      - dev/*
      - chore/*
      - feature/*
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

env:
  NODE_ENV: production

jobs:
  test-on-deno-and-lint:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - windows-latest
          - macOS-latest
    steps:
      - name: Set line ending for Windows
        if: matrix.os == 'windows-latest'
        run: git config --global core.autocrlf false

      - name: Clone repository
        uses: actions/checkout@v7

      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: canary

      - name: Set up Just
        uses: extractions/setup-just@v2

      - name: Deno version
        run: deno --version

      - name: Install dependencies
        run: deno install --vendor

      - name: Lint
        run: just lint

      - name: Test
        run: just test

      - name: Publish dry run
        run: deno publish --dry-run
        if: matrix.os == 'ubuntu-24.04'

  test-on-bun:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - windows-latest
          - macOS-latest
    steps:
      - name: Set line ending for Windows
        if: matrix.os == 'windows-latest'
        run: git config --global core.autocrlf false

      - name: Clone repository
        uses: actions/checkout@v7

      - name: Set up Nub
        uses: nubjs/setup-nub@v0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: nub ci

      - name: Test
        run: bun test

  test-on-node:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 26
          - 24
        os:
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - windows-latest
          - macOS-latest
    steps:
      - name: Set line ending for Windows
        if: matrix.os == 'windows-latest'
        run: git config --global core.autocrlf false

      - name: Clone repository
        uses: actions/checkout@v7

      - uses: nubjs/setup-nub@v0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: nub ci

      - name: Test (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          Get-ChildItem -Recurse -Filter *.test.ts | ForEach-Object {
            nubx tsx --test $_.FullName
          }
        shell: pwsh

      - name: Test (Linux/macOS)
        if: matrix.os != 'windows-latest'
        run: nubx tsx --test **/*.test.ts
